collated: true
status: review
context:
  cite: Marie-Emmanuelle Tano ’21
  quote: The department makes it very easy for students to find ways to bring in and combine other subjects that they may have interest in. Most of the Africana professors are cross-listed with other departments like English, philosophy and art history, so it is cool to learn about their research interests and how they integrate Africana concepts within them.
variants:
  - name: with-image
    context:
      img: https://dummyimage.com/175