default: Row Style
context:
  variant: by-the-numbers--row
  block_variant: stat-block--vertical
  items:
    - stat: 8:1
      stat_caption: Student-to-faculty ratio
      stat_number_classes: text-white
      stat_classes: bg-lavender border-lavender-100
    - stat: '600+'
      stat_caption: Classes offered at Pomona each year
      stat_number_classes: text-white
      stat_classes: bg-orange border-orange-100
    - stat: '52<span>%</span>'
      stat_caption: Students who conduct research with faculty
      stat_number_classes: text-white
      stat_classes: bg-green border-green-100
    - stat: '48'
      stat_caption: Majors offered at Pomona College
      stat_number_classes: text-white
      stat_classes: bg-red border-red-100
variants:
  - name: List Style
    context:
      variant: by-the-numbers--list
      block_variant: stat-block--horizontal
      items:
        - stat: 8:1
          stat_caption: Student-to-faculty ratio
          stat_classes: border-lavender bg-white
          stat_number_classes: text-lavender
        - stat: '600+'
          stat_caption: Classes offered at Pomona each year
          stat_classes: border-orange bg-white
          stat_number_classes: text-orange
        - stat: '52<span>%</span>'
          stat_caption: Students who conduct research with faculty
          stat_classes: border-green bg-white
          stat_number_classes: text-green
        - stat: '48'
          stat_caption: Majors offered at Pomona College
          stat_classes: border-red bg-white
          stat_number_classes: text-red

